// Coded by Ben Wiggins
package gui;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Toolkit;

/**
 *
 * @author Pistol-King
 */
public class Link_Me_Up_Scotty extends javax.swing.JFrame {

    /**
     * Creates new form Link_Me_Up_Scotty
     */
    public Link_Me_Up_Scotty() {
    	setSize(Toolkit.getDefaultToolkit().getScreenSize());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Link_button = new javax.swing.JButton();
        course_link_scroll = new javax.swing.JScrollPane();
        contact_link_scroll = new javax.swing.JScrollPane();
        note_link_scroll = new javax.swing.JScrollPane();
        event_link_scroll = new javax.swing.JScrollPane();
        course_scroll_label = new javax.swing.JLabel();
        event_scroll_label = new javax.swing.JLabel();
        note_scroll_label = new javax.swing.JLabel();
        contact_scroll_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Link_button.setText("Link");
        Link_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Link_buttonActionPerformed(evt);
            }
        });

        course_scroll_label.setText("Courses");

        event_scroll_label.setText("Events");

        note_scroll_label.setText("Notes");

        contact_scroll_label.setText("Contacts");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Link_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(course_link_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, Toolkit.getDefaultToolkit().getScreenSize().width / 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(course_scroll_label, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(event_link_scroll, javax.swing.GroupLayout.PREFERRED_SIZE,  Toolkit.getDefaultToolkit().getScreenSize().width / 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contact_scroll_label, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(note_link_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, Toolkit.getDefaultToolkit().getScreenSize().width / 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(note_scroll_label, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(event_scroll_label, javax.swing.GroupLayout.PREFERRED_SIZE, Toolkit.getDefaultToolkit().getScreenSize().width / 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contact_link_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(course_scroll_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(course_link_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, Toolkit.getDefaultToolkit().getScreenSize().height / 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(event_scroll_label)
                            .addComponent(note_scroll_label)
                            .addComponent(contact_scroll_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(event_link_scroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, Toolkit.getDefaultToolkit().getScreenSize().height / 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(note_link_scroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, Toolkit.getDefaultToolkit().getScreenSize().height / 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contact_link_scroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, Toolkit.getDefaultToolkit().getScreenSize().height / 8, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(Link_button, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        //pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Link_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Link_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Link_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Link_Me_Up_Scotty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Link_Me_Up_Scotty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Link_Me_Up_Scotty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Link_Me_Up_Scotty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Link_Me_Up_Scotty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Link_button;
    private javax.swing.JScrollPane contact_link_scroll;
    private javax.swing.JLabel contact_scroll_label;
    private javax.swing.JScrollPane course_link_scroll;
    private javax.swing.JLabel course_scroll_label;
    private javax.swing.JScrollPane event_link_scroll;
    private javax.swing.JLabel event_scroll_label;
    private javax.swing.JScrollPane note_link_scroll;
    private javax.swing.JLabel note_scroll_label;
    // End of variables declaration//GEN-END:variables
}
